### ISSUE TITLE
NEWS?

### ISSUE THREAD

**Issue by bdubbs** [whot/libevdev#4]
So what changed in version 1.5.8?  I can't find any NEWS file, ChangeLog, or Release Notes.

A NEWS file with a summary of changes would be nice.

**Comment by whot** [comment]
this is a mirror only, not the repository itself. Bugs for libevdev should be filed at http://bugs.freedesktop.org.

But to answer your question: the NEWS file is the git log, please refer to that instead.

**Comment by bdubbs** [comment]
The git log is usually not very informative.  It treats spelling corrections with the same emphasis as api changes.  Some often say things like "Merged request #345" which is totally worthless for a non-developer.

http://en.tldp.org/HOWTO/Software-Release-Practice-HOWTO/distpractice.html

**Comment by whot** [comment]
libevdev is not a fast-moving project, there are only a few commits in each release, shouldn't take more than two minutes to read through it. in addition, I summarise the changes in the announce emails, all linked to from https://freedesktop.org/wiki/Software/libevdev/ [the latest isn't up there yet because of fdo wiki issues]

**Comment by bdubbs** [comment]
I see that now.  How about adding a simple file( named NEWS or CHANGES or ReleaseNotes or similar) to the tarball that says to look at the URL you provided.
